### ISSUE TITLE
No tree growth

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/BSkyBlock#355]
#### Describe the bug

Newly planted sapling does not grow.

#### Steps to reproduce the behavior

- Unregister player from previous island
- /island
- Cut tree
- Plant sapling in original tree location
- Wait patiently
- Observe that sapling does not grow
- Observe that light level = 15 and space is adequate -- same space as original tree
- Finally, cheat with bonemeal to test growth capability -- it does not

#### Expected behavior

- Normal tree growth.

##### Output of `/bbox version` (Mandatory)

```
>bbox version
[09:41:09] [Server thread/INFO]: Running SPIGOT 1.16.1.
[09:41:09] [Server thread/INFO]: BentoBox version: 1.14.1-SNAPSHOT-b1835
[09:41:09] [Server thread/INFO]: Database: JSON
[09:41:09] [Server thread/INFO]: Loaded Game Worlds:
[09:41:09] [Server thread/INFO]: world_skyblock (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
[09:41:09] [Server thread/INFO]: Loaded Addons:
[09:41:09] [Server thread/INFO]: Biomes 1.13.0-SNAPSHOT-b180 (ENABLED)
[09:41:09] [Server thread/INFO]: BSkyBlock 1.13.0-SNAPSHOT-b601 (ENABLED)
[09:41:09] [Server thread/INFO]: Challenges 0.9.0-SNAPSHOT-b420 (ENABLED)
[09:41:09] [Server thread/INFO]: ExtraMobs 1.11.0.4-SNAPSHOT-b7 (ENABLED)
[09:41:09] [Server thread/INFO]: Level 2.3.2-SNAPSHOT-b396 (ENABLED)
```

For reference, Spigot Jenkins build 2827.

**Comment by SlimeDog** [comment]
I executed /is reset (twice) to generate completely new island. Tree growth occurred normally.

**Comment by tastybento** [comment]
I don't know if you've been updating your server as well, but they are fixing bugs with 1.16.1 so maybe there's some ticking issues. There's nothing we're doing to prevent tree growth so this is not really actionable right now.

**Comment by SlimeDog** [comment]
Server is 1.16.1 latest, within 1 hour of each code change. I have a monitor on the Spigot change log.

**Comment by SlimeDog** [comment]
This issue is easily reproducible on my up-to-date Spigot 1.16.1. It might be worth a look.

**Comment by tastybento** [comment]
You write:
 >Finally, cheat with bonemeal to test growth capability -- it does not

Does this mean that even with bonemeal you cannot grow the tree?

**Comment by SlimeDog** [comment]
> Does this mean that even with bonemeal you cannot grow the tree?

That is correct. After the lengthy unsuccessful waiting, I decided to test with bonemeal, just to see if the sapling would grow at all. It would not. I have replicated this sequence three times out of three attempts.

**Comment by tastybento** [comment]
I set up two players on the test server, which is running Paper-90 1.16.1. I planted sampling and waited with F3 enabled to track growth. Both grew into saplings after waiting for sufficient time.

I started taking screenshots after seeing the Sapling Stage move from 0 to 1:
<img width="1073" alt="Screen Shot 2020-07-12 at 5 52 51 PM" src="https://user-images.githubusercontent.com/4407265/87261372-c8a42700-c46a-11ea-87c8-c15f3f8d9d93.png">
<img width="1071" alt="Screen Shot 2020-07-12 at 6 06 39 PM" src="https://user-images.githubusercontent.com/4407265/87261389-d9549d00-c46a-11ea-99f2-00c632320bef.png">
This tree took about 14 minutes to grow.

Here's a totally new island:
**Stage 0**
<img width="856" alt="Screen Shot 2020-07-12 at 5 53 05 PM" src="https://user-images.githubusercontent.com/4407265/87261422-01dc9700-c46b-11ea-8826-7e0c71fc1ca6.png">
**Stage 1**
<img width="856" alt="Screen Shot 2020-07-12 at 5 53 19 PM" src="https://user-images.githubusercontent.com/4407265/87261415-f7220200-c46a-11ea-847b-4b8e9b1273f8.png">
**Fully grown**
<img width="858" alt="Screen Shot 2020-07-12 at 6 06 48 PM" src="https://user-images.githubusercontent.com/4407265/87261444-1b7dde80-c46b-11ea-9bee-4223f62483aa.png">

**Comment by tastybento** [comment]
I just saw your comment about bonemeal not working. That sounds like something is blocking growth completely.

Can you do /is info for this island?

**Comment by tastybento** [comment]
Also try this, set this setting to Active - `/bsb settings` and try again:

<img width="854" alt="Screen Shot 2020-07-12 at 6 15 42 PM" src="https://user-images.githubusercontent.com/4407265/87261640-dad29500-c46b-11ea-8332-b7faf8294b04.png">

**Comment by SlimeDog** [comment]
I do not see that you followed my script, particularly the /unregister player then /island part.

**Comment by tastybento** [comment]
I did follow your sequence. On the island with the cow pig and duck I unregistered, and did /island.

If you cannot grow a tree using bonemeal on your island then yes, it's likely that the tree growth is being blocked by that setting. If you change that setting to Active and bonemeal allows it then that will confirm it. Then we need to find out why BentoBox thinks you are no longer on your island, so do /is info when on the island and look at what it says compared to your coords.

**Comment by SlimeDog** [comment]
The player is OP, but I do not see that he is doing anything OP-restricted.

Original island information
```
>bsbadmin info PLAYER_ELIDED
[18:47:19] [Server thread/INFO]: ========== Island Info ============
[18:47:19] [Server thread/INFO]: UUID: BSkyBlock4ead2e89-b302-40d2-b638-3cce0631f9cb
[18:47:19] [Server thread/INFO]: Owner: PLAYER_ELIDED
[18:47:19] [Server thread/INFO]: Last login: Sun Jul 12 14:00:01 PDT 2020
[18:47:19] [Server thread/INFO]: Deaths: 0
[18:47:19] [Server thread/INFO]: Resets: 0 (Max: 2)
[18:47:19] [Server thread/INFO]: Team members:
[18:47:19] [Server thread/INFO]: PLAYER_ELIDED Owner
[18:47:19] [Server thread/INFO]: Island location: 512,120,512
[18:47:19] [Server thread/INFO]: Island coordinates: 256,0,256 to 767,256,767
[18:47:19] [Server thread/INFO]: Protection range: 128
[18:47:19] [Server thread/INFO]: Largest historical protection range: 128
[18:47:19] [Server thread/INFO]: Protection coordinates: 384,0,384 to 639,256,639
```
```
>bsbadmin unregister PLAYER_ELIDED
```
```
/island
```
which creates a new island (which is unlit, per [#354](https://github.com/BentoBoxWorld/BSkyBlock/issues/354).
Dogs arrived, which may be a hint of bad juju, since per [#1450](https://github.com/BentoBoxWorld/BentoBox/issues/1450) they should not.

```
>bsbadmin info PLAYER_ELIDED
[18:55:53] [Server thread/INFO]: ========== Island Info ============
[18:55:53] [Server thread/INFO]: UUID: BSkyBlock52b106a0-8da8-4031-9c86-c83019fe57fb
[18:55:53] [Server thread/INFO]: Owner: PLAYER_ELIDED
[18:55:53] [Server thread/INFO]: Last login: Sun Jul 12 14:00:01 PDT 2020
[18:55:53] [Server thread/INFO]: Deaths: 0
[18:55:53] [Server thread/INFO]: Resets: 0 (Max: 2)
[18:55:53] [Server thread/INFO]: Team members:
[18:55:53] [Server thread/INFO]: PLAYER_ELIDED Owner
[18:55:53] [Server thread/INFO]: Island location: 0,120,512
[18:55:53] [Server thread/INFO]: Island coordinates: -256,0,256 to 255,256,767
[18:55:53] [Server thread/INFO]: Protection range: 128
[18:55:53] [Server thread/INFO]: Largest historical protection range: 128
[18:55:53] [Server thread/INFO]: Protection coordinates: -128,0,384 to 127,256,639
```
- Cut tree
- Plant sapling
- Wait ...
- Attack sapling with bonemeal, no joy

`Trees growing outside range` is `disabled`. I do not want to change it. We run all default settings.

**Comment by tastybento** [comment]
What is your BSkyblock island config?

It looks like you have an island distance of 512? Did you change that recently?

If you change the tree growth setting to Active **as an experiment**, can you grow the tree via bonemeal? At what location is the tree on this island?

If you change the player to not be Op **as an experiment** can the player place blocks on the island?
If not, run the admin why command and see why he cannot. 

Finally, can you zip up the BentoBox folder (and database) and share it so I can try and replicate?

**Comment by SlimeDog** [comment]
Download of [plugins/BentoBox/addons/BSkyBlock/config.yml](http://blackdog.straight8.com/drops/bsb-config.yml)
Please advise when you have copied it, so I can delete it.

Island distance = 512 since very early on, certainly not recently. I believe that it was set before any islands were created (and the island info -- see above -- certainly reinforces that), but I cannot guarantee it.

I will try `Active` and report back. Sapling is at the location of the original tree.

I will try `non-OP` and report back.

**Comment by SlimeDog** [comment]
`non-OP` test

Made PLAYER_ELIDED non-OP, then
```
>bsbadmin unregister PLAYER_ELIDED
[08:08:50] [Server thread/INFO]: Type command again within 10s to confirm.
>bsbadmin unregister PLAYER_ELIDED
[08:08:52] [Server thread/INFO]: Unregistered player from island at 512,120,512.
[08:09:02] [Server thread/INFO]: PLAYER_ELIDED issued server command: /island
>bsbadmin why
[08:09:46] [Server thread/INFO]: =========== SkyBlock help ===========
[08:09:46] [Server thread/INFO]: /bsbadmin why <player>: toggle console protection debug reporting
[08:09:46] [Server thread/INFO]: =================================
>bsbadmin why PLAYER_ELIDED
[08:09:51] [Server thread/INFO]: Turning on console debug for PLAYER_ELIDED.
[08:10:02] [Server thread/INFO]: [BentoBox] Why: BlockBreakEvent in world world_skyblock at 0,126,512
[08:10:02] [Server thread/INFO]: [BentoBox] Why: PLAYER_ELIDED BREAK_BLOCKS - NOT_ALLOWED_IN_WORLD
>bsbadmin info PLAYER_ELIDED
[08:13:07] [Server thread/INFO]: ========== Island Info ============
[08:13:07] [Server thread/INFO]: UUID: BSkyBlock73b2e11d-7528-4a6f-bca3-a99c48f3a1b6
[08:13:07] [Server thread/INFO]: Owner: PLAYER_ELIDED
[08:13:07] [Server thread/INFO]: Last login: Mon Jul 13 07:47:31 PDT 2020
[08:13:07] [Server thread/INFO]: Deaths: 0
[08:13:07] [Server thread/INFO]: Resets: 0 (Max: 2)
[08:13:07] [Server thread/INFO]: Team members:
[08:13:07] [Server thread/INFO]: PLAYER_ELIDED Owner
[08:13:07] [Server thread/INFO]: Island location: 0,120,512
[08:13:07] [Server thread/INFO]: Island coordinates: -256,0,256 to 255,256,767
[08:13:07] [Server thread/INFO]: Protection range: 128
[08:13:07] [Server thread/INFO]: Largest historical protection range: 128
[08:13:07] [Server thread/INFO]: Protection coordinates: -128,0,384 to 127,256,639
```
`/island reset` produces the [infamous](https://bugs.mojang.com/browse/MC-191388)
```
[08:14:32] [Server thread/ERROR]: No key position_predicate in MapLike[{location_predicate:{predicate_type:"minecraft:always_true"},output_state:{Name:"minecraft:mossy_cobblestone"},input_predicate:{predicate_type:"minecraft:random_block_match",probability:0.2f,block:"minecraft:cobblestone"}}]
```
and many, many more similar console/log errors.
But the new island is created, on which the player can break blocks.
```
>bsbadmin info PLAYER_ELIDED
[08:17:35] [Server thread/INFO]: ========== Island Info ============
[08:17:35] [Server thread/INFO]: UUID: BSkyBlock613acb54-0578-4eb3-b83e-5dcb3cff0699
[08:17:35] [Server thread/INFO]: Owner: PLAYER_ELIDED
[08:17:35] [Server thread/INFO]: Last login: Mon Jul 13 07:47:31 PDT 2020
[08:17:35] [Server thread/INFO]: Deaths: 0
[08:17:35] [Server thread/INFO]: Resets: 1 (Max: 2)
[08:17:35] [Server thread/INFO]: Team members:
[08:17:35] [Server thread/INFO]: PLAYER_ELIDED Owner
[08:17:35] [Server thread/INFO]: Island location: 512,120,0
[08:17:35] [Server thread/INFO]: Island coordinates: 256,0,-256 to 767,256,255
[08:17:35] [Server thread/INFO]: Protection range: 128
[08:17:35] [Server thread/INFO]: Largest historical protection range: 128
[08:17:35] [Server thread/INFO]: Protection coordinates: 384,0,-128 to 639,256,127
```

**Comment by SlimeDog** [comment]
Do you still need the "Active" test, or did the non-OP test provide enough information?

**Comment by tastybento** [comment]
This looks suspicious:
> [08:10:02] [Server thread/INFO]: [BentoBox] Why: PLAYER_ELIDED BREAK_BLOCKS - NOT_ALLOWED_IN_WORLD

What happened here? Did he try to break a block on the island? Can you do F3 and actually check where the coordinates are? Also, does this player have a range perm on him such that the island range is changing? (I assume not, but just checking).

**Comment by SlimeDog** [comment]
I would say more than suspicious -- indicative. It was the result of trying to chop a log out of the tree (as OP, I was able to chop the tree, but not as non-OP). The coordinate was 0,126,512 -- the second block from the bottom of the original tree.

**Comment by tastybento** [comment]
Why is the player at that location? 0, 126, 512? His island is at 512,120,0...

**Comment by tastybento** [comment]
Okay, a few questions:

1. Is this repeatable? It is that every time you unregister, then make an island, you cannot interact with it until you reset?
2. Is it just this player, or any other?
3. Can you share your BentoBox folder zipped up so I can try it?

**Comment by SlimeDog** [comment]
> Why is the player at that location? 0, 126, 512? His island is at 512,120,0... oh wait - I see. Let me study this...

You're looking at the third island. Look at the second (failing) island.

**Comment by SlimeDog** [comment]
> Okay, a few questions:
> 
> 1. Is this repeatable? It is that every time you unregister, then make an island, you cannot interact with it until you reset?

Correct.

> 2. Is it just this player, or any other?

I have two test players.
The first -- PLAYER_ELIDED above -- is usually OP, but was de-OP'd as requested for the later tests. His original island is moderately developed -- level 127. The failure is repeatable.
The second is new for every test (I restart testing on backups of a known configuration). The failure did not occur for the second player, although the `No key position_predicate in MapLike` error occurred.

> 3. Can you share your BentoBox folder zipped up so I can try it?

http://blackdog.straight8.com/drops/BBox.zip
Again, please let me know when you have it, so I can remove it.

**Comment by tastybento** [comment]
Downloaded.

**Comment by tastybento** [comment]
I managed to replicate this with your database. I haven't worked out why it's happening yet, but I have an island that isn't mine but should be. It survives even after a reboot. Investigating...

**Comment by SlimeDog** [comment]
What a relief. Thanks.

**Comment by tastybento** [comment]
I'm a bit brain frazzled right now. I'll need to look at this tomorrow.

**Comment by SlimeDog** [comment]
No hurry at this end. I get around it easily. I just thought that you would want to figure it out, it case it goes deeper or wider.

**Comment by tastybento** [comment]
I found the offending database entry - it's an island file called 0d6b9b3c-a0a1-49f2-9cd4-a0d3141d3c64.json. This file must be from a long time ago because it's not prefixed with the addon name. This island file has a range of only 128 and not 256. When this file is deleted, things start working again. I think it's messing with the grid manager somehow. Anyway, I suspect it's a left-over from a previous install you did and maybe didn't get deleted? Try and remove it and let me know if it fixes the issue for you.

**Comment by SlimeDog** [comment]
Removing that file resolved the issue.

As you know, I have been testing BentoBox/BSkyBlock from the first dev release. The data presentation has changed radically over time. Newer releases do not detect leftover potential problems, so it has proved very difficult to upgrade across releases (it is relatively easy to start over, of course). Obviously, a lot of the burden is (and should be) on me, since you have made it abundantly clear that change is the norm. I voluntarily decided to test dev releases, although I must say that testing by me and others has identified a large number of issues. So just saying... 

Thanks for taking the time and energy to identify this issue.

**Comment by tastybento** [comment]
@SlimeDog I am very glad that you do this, thank you! Your support is critical.

**Comment by SlimeDog** [comment]
Confirmed fixed in BBox 1.15.0-b1839

Shutting it down seems a bit harsh, but I guess it will get their attention. :)

**Comment by tyleraharrison** [comment]
Problem is resolved for me as well in snapshot 1.15.0 b1846

**Comment by Baterka** [comment]
Bug still persist for somw players wirh Release 1.15.0 (https://github.com/BentoBoxWorld/BentoBox/releases/tag/1.15.0) on 1.16.2 PaperMC (latest build)

**Comment by tastybento** [comment]
@Baterka This bug is closed and contained multiple issues. I don't know what specifically you are referring to, so please file another.
